<!-- Import Featurebase SDK -->
<script>
    !(function(e,t){const a="featurebase-sdk";function n(){if(!t.getElementById(a)){var e=t.createElement("script");(e.id=a),(e.src="https://do.featurebase.app/js/sdk.js"),t.getElementsByTagName("script")[0].parentNode.insertBefore(e,t.getElementsByTagName("script")[0])}}"function"!=typeof e.Featurebase&&(e.Featurebase=function(){(e.Featurebase.q=e.Featurebase.q||[]).push(arguments)}),"complete"===t.readyState||"interactive"===t.readyState?n():t.addEventListener("DOMContentLoaded",n)})(window,document);
</script>

<!-- Embed Featurebase -->
<div data-featurebase-embed></div>

<!-- Identify user in Featurebase -->
<script>
    Featurebase('embed', {
        /* Required */
        organization: 'southpole',
    })
</script>
