<button data-feedbear-button>Feedback?</button>
<script>
    (function (w, d, s, o, f, js, fjs) {
        w[o] = w[o] || function () { (w[o].q = w[o].q || []).push(arguments) };
        js = d.createElement(s), fjs = d.getElementsByTagName(s)[0];
        js.id = o; js.src = f; js.async = 1;
        fjs.parentNode.insertBefore(js, fjs);
    }(window, document, 'script', 'FeedBear', 'https://sdk.feedbear.com/widget.js'));

    FeedBear("button", {
        element: document.querySelector("[data-feedbear-button]"),
        project: "southpole",
        board: "feature-requests",
        jwt: null // see step 3,
    });
</script>